name: Publish NPM module

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
        with:
          oidc-provider-name: github
          oidc-audience: jfrog-github

      - name: JFrog CLI
        run: |
          jf npm-config --repo-deploy=npm-mmig --repo-resolve=npm
          jf npm install --build-name my-npm-build --build-number 1
          jf rt bce my-npm-build 1
          jf rt bag my-npm-build 1
          jf npm publish --build-name my-npm-build --build-number 1
          jf rt bp my-npm-build 1