name: Publish NPM module

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
        with:
          oidc-provider-name: github
          oidc-audience: jfrog-github

      - name: Configure repositories
        run: jf npm-config --repo-deploy=npm-mmig --repo-resolve=npm

      - name: Install dependencies
        run: |
          ls -la
          jf npm install

      - name: Publish package
        run: jf npm publish 
            
          